### ISSUE TITLE
Post-processing effects are creating rendering artifacts on Safari 15.4

### ISSUE THREAD

**Issue by iXperiential** [playcanvas/engine#4136]
https://forum.playcanvas.com/t/ios-15-4-broke-the-post-processing-effects/24817

### Description

On Safari 15.4 (iOS or macOS), using post processing effects causes rendering artifacts.
Sample project:
https://developer.playcanvas.com/en/tutorials/custom-posteffect/

### Steps to Reproduce

1. Open the project with Safari 15.4

Potential cause:
https://bugs.webkit.org/show_bug.cgi?id=237230

![MicrosoftTeams-image](https://user-images.githubusercontent.com/60481587/158644738-44d823c0-c58b-4517-8098-7e6609dbd58f.png)

**Comment by mvaligursky** [comment]
I see the same on Safari 15.3, and also Chrome, as so I don't think this is 15.4 issue.

**Comment by willeastcott** [comment]
https://bugs.webkit.org/show_bug.cgi?id=237906

**Comment by mvaligursky** [comment]
created webkit issue: https://bugs.webkit.org/show_bug.cgi?id=238022

**Comment by iXperiential** [comment]
> I don't have access to macOS 15.4 - @iXperiential - would you be able to open the "Custom Post Process" project you linked, likely clone it, and disable Antialiasing in the Settings, to see if the problem goes away for you. **Settings->Rendering->Anti-Alias**.

I confirm it's working as intended with AA off.
![Capture](https://user-images.githubusercontent.com/60481587/158873650-b2924fe5-16f8-42e6-a154-e23a41a939f4.JPG)

**Comment by iXperiential** [comment]
In our app (not the test one), I can confirm that it works as fine without the AA.
And from what I know, PC bypasses the AA anyway when it uses post processing effects.

**Comment by mvaligursky** [comment]
reopening even though we have a workaround getting released, to keen an eye on an actual fix on webkit side.

**Comment by mvaligursky** [comment]
This is marked as fixed here now: https://bugs.webkit.org/show_bug.cgi?id=238022
`Fixed in the ANGLE roll https://bugs.webkit.org/show_bug.cgi?id=238171`

**Comment by mvaligursky** [comment]
update on the webkit ticket:
`Just to let everyone know, the fix for this has shipped in Safari 15.5.`

**Comment by mvaligursky** [comment]
This is confirmed as working in 15.5 by @slimbuck , closing.

**Comment by lukasharing** [comment]
Still happens in my ipad 2020, in our ionic app, inside a webview:

User agent is:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
``` 

It seems that deactivating antialias, it works fine!

**Comment by yaustar** [comment]
@lukasharing What version of iOS is it running?

**Comment by lukasharing** [comment]
IOS VERSION 15.4.1

**Comment by lukasharing** [comment]
Yes, it is using safari webview.

**Comment by yaustar** [comment]
> IOS VERSION 15.4.1

The issue was fixed in iOS 15.5 on Apple's side which is why you are still seeing the error on 15.4

**Comment by lukasharing** [comment]
Yup, the agent check is incorrect
